spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd
  profiles:
    active: local
    include: secret

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  tomcat:
    access-log:
      enabled: true
  port: 8081

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"